name: mycar
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+145  # Feature update
environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  #State Mangement
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  #Local Storage
  shared_preferences: ^2.3.2
  #Network Connection
  dio: ^5.7.0
  socket_io_client: ^1.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  #UI
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  toastification: ^2.3.0
  # skeletonizer: ^1.4.2
  multi_select_flutter: ^4.1.3
  flutter_svg: ^2.0.16
  global_configuration: ^2.0.0
  flutter_carousel_widget: ^3.1.0
  intl: ^0.19.0
  gap: ^3.0.1
  #Data
  freezed: ^2.5.7
  #Dependency Injection
  injectable: ^2.5.0
  get_it: ^8.0.2
  injectable_generator: ^2.6.2
  #Navigation
  go_router: ^14.4.1
  go_provider: ^1.7.0
  #Permissions
  permission_handler: ^11.3.1
  #Location
  latlong2: ^0.9.1
  flutter_boring_avatars: ^2.0.1
  any_link_preview: ^3.0.2
  camera: ^0.11.0+2
  record: ^5.2.0
  path_provider: ^2.1.5
  audio_waveforms: ^1.2.0
  flutter_download_manager: ^0.5.5
  cached_video_player_plus: ^3.0.3
  flutter_credit_card: ^4.0.1
  video_thumbnail: ^0.5.6
  open_filex: ^4.7.0
  easy_image_viewer: ^1.5.1
  downloadsfolder: ^1.2.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  webview_flutter: ^4.10.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  voice_message_package: ^2.2.1
  avatar_glow: ^3.0.1
  video_compress: ^3.1.4
  logger: ^2.5.0
  uuid: ^4.5.1
  intl_utils: ^2.8.10
  flutter_local_notifications: ^19.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5 
  

dependency_overrides: 
  intl: ^0.20.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/cfg/app_settings.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300

flutter_intl:
  enabled: true
  class_name: S
  main_locale: ar
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false